#Pantalla SDL
SCREEN_WIDTH: 1800

#Las posibles teclas del jugador son:
# "FlechitaDerecha", "FlechitaIzquierda", "FlechitaArriba", "FlechitaAbajo", "T", 
# "W", "S", "D", "M", "A", "1", "2", "3", "4", "SpaceBar";
KEY_COMMAND_MOVE_RIGHT: "FlechitaArriba"
KEY_COMMAND_MOVE_LEFT: "FlechitaAbajo"
KEY_COMMAND_MOVE_UP: "FlechitaIzquierda"
KEY_COMMAND_MOVE_DOWN: "FlechitaDerecha"
KEY_COMMAND_TURBO: "T"
KEY_COMMAND_JUMP: "SpaceBar"
KEY_COMMAND_TURN: "S"
KEY_COMMAND_FLIP_SHOT: "1"
KEY_COMMAND_RED_SHOT: "2"
KEY_COMMAND_PRUPLE_SHOT: "3"
KEY_COMMAND_GOLDEN_SHOT: "4"
KEY_COMMAND_PAUSE_MUSIC: 'M'
KEY_COMMAND_NEXT_MUSIC: 'N'
KEY_COMMAND_SKIP_REPLAY: 'R'

