test: 40

#Partida
GAME_TIME: 180000.0 #Milisegundos
EXTRA_TIME: 30000.0
REPLAY_TIME: 5000.0
FRAME_RATE: 40000.0

#Jugador
FLIP_IMPULSE: 3000.0
PI:  3.14159265358979323846
FLIP_ANGULAR_VEL: 6.28   #PI*2
ROTATION_ANGULAR_VELOCITY: 3.0
CAR_HALF_WIDTH: 7.5
CAR_HALF_HEIGHT: 2.0
TURBO_FORCE: 4000.0
JUMP_IMPULSE: 40.0
MOVEMENT_FORCE: 500.0
CAR_FRICTION: 1.5
FRONT_SENSOR_HALF_WIDTH: 5.0
BOTTOM_SENSOR_HALF_HEIGHT: 5.0

#Terreno de juego (caja de box2d)
FIELD_HALF_WIDTH: 90.0
FIELD_HEIGHT: 60.0
WALL_WIDTH: 1.0
GROUND_FRICTION: 1.0

#Arcos
GOAL_TOP_HALF_WIDTH: 10.0
GOAL_TOP_HALF_HEIGHT: 22.0

#Parametros necesarios en box2d
GRAVITY: -10.0
TORQUE_FORCE: 5000.0
TORQUE_IMPULSE: 200.0

#Pelota
BALL_RADIUS: 5.0

#Fuerza tiros especiales
RED_SHOT_IMPULSE: 100000.0
GOLD_SHOT_IMPULSE: 100000.0
PURPLE_SHOT_IMPULSE: 100000.0
SPECIAL_SHOT_TIME: 25.0 #Cantidad de frames que dura el tiro especial